[package]
org = "chintanawilamuna"
name = "AuthJH"
version = "1.0.1"
export = ["AuthJH"]
distribution = "2201.3.1"
keywords = ["choreo-apim-mediation-policy","choreo-apim-mediation-request-flow"]

[build-options]
observabilityIncluded = true
