[package]
org = "chintanawilamuna"
name = "JHAuthPolicy"
version = "1.1.3"
export = ["JHAuthPolicy"]
distribution = "2201.3.1"
keywords = ["choreo-apim-mediation-policy","choreo-apim-mediation-request-flow"]

[build-options]
observabilityIncluded = true
